name: borg
description: Command line tool to manage configuration of Dart mono repo
version: 1.0.0
homepage: https://github.com/alexei-sintotski/dart-borg

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  dependency_validator: ^1.4.0
